spring:
    jpa:
      properties.hibernate.dialect: org.hibernate.dialect.MySQL5InnoDBDialect
      hibernate.ddl-auto: update
      show-sql: true
jwt:
   secret: strangergymhahaha
   expiration: 60000